# CreditoSys/docker-compose.yml
#version: '3.8'

services:
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: credsys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/media:/media
      - ./backend/static:/static
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - web
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: creditosys-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@creditosys.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80" # Accede a pgAdmin4 en http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

