# Generated by Django 5.2.3 on 2025-07-23 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_documento', models.FileField(upload_to='documentos_dni/')),
                ('ingresos_documento', models.FileField(upload_to='documentos_ingresos/')),
            ],
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('valido', 'Válido')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_minimo_aprobacion', models.IntegerField(default=70, help_text='Score mínimo para aprobación automática')),
                ('score_minimo_revision', models.IntegerField(default=50, help_text='Score mínimo para revisión manual')),
                ('monto_maximo_aprobacion', models.DecimalField(decimal_places=2, default=100000, help_text='Monto máximo para aprobación automática', max_digits=12)),
                ('peso_historial_crediticio', models.IntegerField(default=40, help_text='Peso del historial crediticio (%)')),
                ('peso_ingresos_deuda', models.IntegerField(default=30, help_text='Peso de ingresos vs deuda (%)')),
                ('peso_activos', models.IntegerField(default=20, help_text='Peso de activos (%)')),
                ('peso_comportamiento', models.IntegerField(default=10, help_text='Peso de comportamiento (%)')),
                ('requiere_recibos_sueldo', models.BooleanField(default=True)),
                ('requiere_historial_crediticio', models.BooleanField(default=True)),
                ('requiere_declaracion_renta', models.BooleanField(default=False)),
                ('requiere_estados_cuenta', models.BooleanField(default=False)),
                ('requiere_escrituras_propiedad', models.BooleanField(default=False)),
                ('tiempo_maximo_validacion', models.IntegerField(default=3, help_text='Tiempo máximo de validación en días')),
                ('tamano_maximo_archivo', models.IntegerField(default=50, help_text='Tamaño máximo de archivo en MB')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Política',
                'verbose_name_plural': 'Configuraciones de Políticas',
            },
        ),
    ]
