# Generated by Django 5.2.3 on 2025-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_evaluated_at_application_evaluated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='activos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='comportamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='historial_crediticio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ingresos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
