# Generated by Django 5.2.3 on 2025-07-23 04:07

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario_creado', 'Usuario Creado'), ('politica_actualizada', 'Política Actualizada'), ('backup_completado', 'Backup Completado')], max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('morosidad', 'Alta Morosidad'), ('rendimiento', 'Bajo Rendimiento'), ('cpu', 'Uso de CPU Alto'), ('sistema', 'Problema del Sistema')], max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('mensaje', models.TextField()),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_destinatario', models.EmailField(max_length=254)),
                ('enviado_exitosamente', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Enviada',
                'verbose_name_plural': 'Alertas Enviadas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='AlertasConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerta_morosidad', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje de morosidad para activar alerta', max_digits=5)),
                ('alerta_rendimiento', models.DecimalField(decimal_places=2, default=85.0, help_text='Porcentaje mínimo de rendimiento', max_digits=5)),
                ('alerta_cpu', models.DecimalField(decimal_places=2, default=80.0, help_text='Porcentaje máximo de uso de CPU', max_digits=5)),
                ('email_alertas', models.EmailField(default='admin@empresa.com', help_text='Email para recibir notificaciones de alertas', max_length=254)),
                ('alertas_activas', models.BooleanField(default=True, help_text='Si las alertas están habilitadas')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('solicitud_creada', 'Solicitud Creada'), ('solicitud_actualizada', 'Solicitud Actualizada'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('documento_subido', 'Documento Subido'), ('politica_actualizada', 'Política Actualizada'), ('usuario_creado', 'Usuario Creado'), ('usuario_actualizado', 'Usuario Actualizado'), ('usuario_eliminado', 'Usuario Eliminado'), ('rol_cambiado', 'Rol Cambiado'), ('sistema_backup', 'Backup del Sistema'), ('sistema_restaurado', 'Sistema Restaurado'), ('configuracion_cambiada', 'Configuración Cambiada'), ('acceso_denegado', 'Acceso Denegado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('recurso', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='exitoso', max_length=20)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='users_audit_timesta_45d1d4_idx'), models.Index(fields=['tipo_accion'], name='users_audit_tipo_ac_47dd4f_idx'), models.Index(fields=['usuario'], name='users_audit_usuario_622fef_idx'), models.Index(fields=['estado'], name='users_audit_estado_2e6c04_idx')],
            },
        ),
    ]
